#!/bin/sh

ADMIN_PASSWORD=$(uuidgen)

function setup_keystone_auth() {
    sed -i 's#%SERVICE_TENANT_NAME%#systenant#' "$@"
    sed -i 's#%SERVICE_USER%#admin#' "$@"
    sed -i "s#%SERVICE_PASSWORD%#${ADMIN_PASSWORD}#" "$@"
}

#######################################################################
cd /etc/glance
sed -i 's#^sql_connection.*#sql_connection = mysql://nova:nova@main-node/glance#' glance-registry.conf 

echo '[paste_deploy]
flavor = keystone' >> glance-api.conf

echo '[paste_deploy]
flavor = keystone' >> glance-registry.conf

setup_keystone_auth glance-{registry,api}-paste.ini
echo "glance config is updated"
#######################################################################
cd /etc/nova
echo 'auth_strategy = keystone' >> nova.conf

setup_keystone_auth api-paste.ini
echo "nova config is updated"

#######################################################################
cd /etc/keystone/
sed -i 's#\./etc#/etc#' keystone.conf 
sed -i 's#^connection.*#connection = mysql://nova:nova@main-node/keystone#' keystone.conf 
sed -i 's#backends.kvs#backends.sql#' keystone.conf 
sed -i 's#localhost#main-node#' default_catalog.templates 

service keystone restart
keystone --endpoint http://main-node:35357/v2.0 --token ADMIN user-password-update --pass $ADMIN_PASSWORD 1
keystone --endpoint http://main-node:35357/v2.0 --token ADMIN user-role-add --user 1 --role 1 --tenant_id 1

echo "keystone config is updated"
