#!/bin/sh

function purge() {
    rm -rfv /etc/{glance,nova,keystone}
}

case "$1" in
    backup)
	tar -cvf "${2:-openstack-conf.tar}" /etc/{glance,nova,keystone}
	;;
    update)
	purge
	tar -xvf "$2" -C /
	;;
    purge)
	purge
	;;
esac
