#!/bin/sh -e

yum -y install libvirt mysql-server MySQL-python
for srv in libvirtd mysqld rabbitmq-server; do
    chkconfig $srv on
    /etc/init.d/$srv start
done

PKGS="openstack-glance
 openstack-keystone
 python-novaclient
 openstack-nova-api
 openstack-nova-compute
 openstack-nova-network
 openstack-nova-objectstore
 openstack-nova-scheduler
 openstack-nova-volume
"

if [ "x$1" = "xessex" ]; then
    echo "installing essex"
    OLD_PKGS="$PKGS"
    PKGS=""
    for p in $OLD_PKGS; do
	PKGS="$PKGS $(echo $p |  sed -r 's/([a-z]+-[a-z]+)/\1-essex/')"
    done
else
    echo "installing diablo"
fi

yum install $PKGS python-keystoneclient
