#!/bin/sh

DIRS="$(ls -d /usr/bin/{keystone,nova,glance}*  \
/etc/{keystone,nova,glance} \
/var/{lib,log,run}/{keystone,nova,glance} \
/usr/lib/python*/site-packages/*{keystone,nova,glance}* \
/etc/init.d/{keystone,glance}-* \
/etc/init.d/nova-[^b]* 2>/dev/null)"

function get_date() {
    date '+%Y.%m.%d-%H.%M'
}

function do_install() {
    PKGS="openstack-glance
 openstack-keystone
 python-novaclient
 openstack-nova-api
 openstack-nova-compute
 openstack-nova-network
 openstack-nova-objectstore
 openstack-nova-scheduler
 openstack-nova-volume
"

    case "$1" in
        essex)
            OLD_PKGS="$PKGS"
            PKGS=""
            for p in $OLD_PKGS; do
	        PKGS="$PKGS $(echo $p |  sed -r 's/([a-z]+-[a-z]+)/\1-essex/')"
            done
            ;;
        diablo)
            ;;
        *)
            echo "usage: $0 install (essex|diablo) [-y]"
            exit 1
            ;;
    esac
    
    echo "installing $1"
    shift
    
    yum install libvirt mysql-server MySQL-python "$@"
    yum install $PKGS python-keystoneclient "$@"
}


function do_erase() {
    PKGS="
$(rpm -qa 'openstack*')
$(rpm -qa 'python-(glance|nova|keystone)*')
"
    yum erase $PKGS "$@"
}

ACTION="$1"
shift

case "$ACTION" in
    install)
        do_install "$@"
        ;;
    erase)
        do_erase
        ;;
    purge)
        rm -rfv $DIRS 
        ;;
    dump)
        tar -cf "${1:-.}/openstack-dump.$(get_date).tar" $DIRS
        ;;
    *)
        echo "Usage: $0 (install|erase|purge|dump)"
        exit 1
        ;;
esac
