#!/bin/sh -e

service mysqld start
mysqladmin -uroot password nova || true

#regen db
DB_NAME=nova
DB_USER=nova
DB_PASS=nova
PWD=nova

CC_HOST="127.0.0.1 $(hostname) localhost" # IPv4 address
#HOSTS='node1 node2 node3' # compute nodes list

recreate() {
    echo "recreating $DB_NAME"
    mysqladmin -uroot -p$PWD -f drop $DB_NAME || true
    mysqladmin -uroot -p$PWD create $DB_NAME
}

grant() {
    echo "granting access to $DB_NAME"
    for h in $HOSTS $CC_HOST; do
        echo "GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'$h' IDENTIFIED BY '$DB_PASS';" | mysql -uroot -p$DB_PASS mysql
    done
    echo "GRANT ALL PRIVILEGES ON $DB_NAME.* TO $DB_USER IDENTIFIED BY '$DB_PASS';" | mysql -uroot -p$DB_PASS mysql
    echo "GRANT ALL PRIVILEGES ON $DB_NAME.* TO root IDENTIFIED BY '$DB_PASS';" | mysql -uroot -p$DB_PASS mysql
}

ACTION=grant

if [ -n "$1" ]; then
    ACTION=$1

    if [ -n "$2" ]; then
        DB_NAME="$2"
    fi
fi

if [ "x$ACTION" = "xrecreate" ]; then
    recreate
fi

grant

echo "done!"
