#!/bin/sh

start()
{
    for i in api compute network objectstore scheduler vncproxy; do
        service nova-$i start
    done
    for i in api registry; do
        service glance-$i start
    done
    if [ -r /etc/init.d/keystone ]; then
        service keystone start
    fi
    service httpd start
}

stop()
{
    service httpd stop
    if [ -r /etc/init.d/keystone ]; then
        service keystone stop
    fi
    for i in registry api; do
        service glance-$i stop
    done
    for i in billing-heart billing-os-amqp vncproxy scheduler objectstore network compute api direct-api; do
        [ -x /etc/init.d/nova-$i ] && service nova-$i stop
    done
    rm -fv /var/run/{nova,glance}/*pid
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: osng-services {start|stop|restart}"
        ;;
esac

