#!/bin/sh

PACKAGE="${1%.spec}"

BASE_PATH="/mnt/home/alessio/job/cvs/griddynamics/pioneer"

SRC_ORIG="$BASE_PATH/$PACKAGE"

if [ ! -d "$SRC_ORIG" ]; then
	SRC_ORIG="$PWD"
fi

RPM_SRC_DIR=/root/rpmbuild/SOURCES
VERSION=$(grep "Version:" "$SRC_ORIG/$PACKAGE.spec" |perl -pe 's/[Va-z:]*\s*//')
SRC_VERSIONED="$RPM_SRC_DIR/$PACKAGE-$VERSION"

echo "Removing $SRC_VERSIONED"
rm -rf "$SRC_VERSIONED"

echo "Copying $SRC_ORIG -> $SRC_VERSIONED"
cp -a "$SRC_ORIG" "$SRC_VERSIONED"

sed -i 's/Release: .*/Release:        '$(date +'0.%Y%m%d.%H%M')'%{?dist}/' "$SRC_VERSIONED/$PACKAGE.spec"

echo "Tarring $SRC_VERSIONED"
( cd "$RPM_SRC_DIR" && tar -cf "$PACKAGE-$VERSION.tar.gz" "$PACKAGE-$VERSION")

rpmbuild -ba "$SRC_VERSIONED/$PACKAGE.spec"
